### PR TITLE
Downcase Email

### PR DESCRIPTION
**Pull request by dhosterman**
When registering or signing in, the email is currently case sensitive. This change downcases the email both before creating the User and before checking against an existing User.

### CODE REVIEW

**Comment by shankardevy** [comment]
super cool!

**Comment by shankardevy** [comment]
@dhosterman if you can update the Readme with information on how to use the auth plug, it would be great!

**Comment by dhosterman** [comment]
@shankardevy I did! You removed it when you changed the Travis and Coveralls badge URIs. ;) I've got some other ideas I'd like to contribute as I have time, and I'm very interested in learning Elixir, so I hope you don't mind if I continue to work on this project.

**Comment by shankardevy** [comment]
Contributions are always welcome! Please create an issue with your
suggestions.

On Sun, May 24, 2015 at 10:53 PM, Daniel Hosterman <notifications@github.com

**Pull request merged**
